# Generated by Django 5.2.15 on 2026-10-08 09:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('reddit_post', 'Reddit post'), ('reddit_comment', 'Reddit comment'), ('reddit_dm', 'Reddit DM'), ('discord_channel', 'Discord channel post'), ('discord_dm', 'Discord DM'), ('email', 'Email'), ('other', 'Other')], max_length=32)),
                ('identifier', models.CharField(db_index=True, max_length=512)),
                ('opted_out', models.BooleanField(default=False)),
                ('opted_out_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('channel', 'identifier')},
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('reddit', 'Reddit'), ('discord', 'Discord'), ('email', 'Email (scraped)'), ('tapas', 'Tapas'), ('webtoon', 'Webtoon'), ('behance', 'Behance'), ('artstation', 'ArtStation'), ('globalcomix', 'GlobalComix'), ('facebook', 'Facebook'), ('x', 'X / Twitter'), ('instagram', 'Instagram'), ('other', 'Other')], db_index=True, max_length=32)),
                ('source_uid', models.CharField(db_index=True, max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('headline', models.CharField(blank=True, max_length=512)),
                ('bio', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('qualified', 'Qualified'), ('contacted', 'Contacted'), ('replied', 'Replied'), ('negotiating', 'Negotiating'), ('won', 'Won'), ('lost', 'Lost'), ('disqualified', 'Disqualified')], db_index=True, default='new', max_length=32)),
                ('signal_score', models.IntegerField(db_index=True, default=0)),
                ('signal_count', models.IntegerField(default=0)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'status'], name='core_lead_source_69e69a_idx'), models.Index(fields=['-signal_score'], name='core_lead_signal__0b009a_idx'), models.Index(fields=['-last_seen_at'], name='core_lead_last_se_4c9b2a_idx')],
                'unique_together': {('source', 'source_uid')},
            },
        ),
        migrations.CreateModel(
            name='ContactMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('reddit_post', 'Reddit post'), ('reddit_comment', 'Reddit comment'), ('reddit_dm', 'Reddit DM'), ('discord_channel', 'Discord channel post'), ('discord_dm', 'Discord DM'), ('email', 'Email'), ('other', 'Other')], max_length=32)),
                ('identifier', models.CharField(db_index=True, max_length=512)),
                ('is_primary', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.lead')),
            ],
        ),
        migrations.CreateModel(
            name='OutreachLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('reddit_post', 'Reddit post'), ('reddit_comment', 'Reddit comment'), ('reddit_dm', 'Reddit DM'), ('discord_channel', 'Discord channel post'), ('discord_dm', 'Discord DM'), ('email', 'Email'), ('other', 'Other')], max_length=32)),
                ('send_method', models.CharField(choices=[('automated', 'Automated'), ('manual', 'Manual (human-approved)'), ('hybrid', 'Hybrid (automated prep, manual send)')], max_length=16)),
                ('subject', models.CharField(blank=True, max_length=512)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped (opt-out / rule block)'), ('awaiting_approval', 'Awaiting human approval')], default='pending', max_length=32)),
                ('error_message', models.TextField(blank=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('external_url', models.URLField(blank=True)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreaches', to='core.contactmethod')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreaches', to='core.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('reddit_post', 'Reddit post'), ('reddit_comment', 'Reddit comment'), ('reddit_dm', 'Reddit DM'), ('discord_channel', 'Discord channel post'), ('discord_dm', 'Discord DM'), ('email', 'Email'), ('other', 'Other')], max_length=32)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_positive', models.BooleanField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.lead')),
                ('outreach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.outreachlog')),
            ],
        ),
        migrations.CreateModel(
            name='SendQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_after', models.DateTimeField(db_index=True)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outreach', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='core.outreachlog')),
            ],
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('reddit', 'Reddit'), ('discord', 'Discord'), ('email', 'Email (scraped)'), ('tapas', 'Tapas'), ('webtoon', 'Webtoon'), ('behance', 'Behance'), ('artstation', 'ArtStation'), ('globalcomix', 'GlobalComix'), ('facebook', 'Facebook'), ('x', 'X / Twitter'), ('instagram', 'Instagram'), ('other', 'Other')], db_index=True, max_length=32)),
                ('signal_type', models.CharField(choices=[('new_project_launch', 'New project launched'), ('schedule_slipping', 'Update schedule slipping'), ('solo_creator', 'Doing everything themselves'), ('writer_no_artist', 'Writer / no artist attached'), ('art_frustration', 'Frustration with art'), ('seeking_collab', 'Mentions seeking collaborator'), ('crowdfund_struggle', 'Crowdfunding underperforming'), ('bio_seeking_artist', "Bio says 'looking for artist'"), ('artist_interest', 'Interacting with multiple artists'), ('between_projects', 'Between projects / just finished'), ('public_lfa', "Public 'looking for artist' post"), ('other', 'Other')], db_index=True, max_length=32)),
                ('confidence', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2)),
                ('source_url', models.URLField(blank=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('summary', models.CharField(blank=True, max_length=512)),
                ('evidence', models.TextField(blank=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('detected_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='core.lead')),
            ],
        ),
        migrations.AddField(
            model_name='outreachlog',
            name='signal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreaches', to='core.signal'),
        ),
        migrations.AddIndex(
            model_name='contactmethod',
            index=models.Index(fields=['channel', 'identifier'], name='core_contac_channel_0ebeb0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contactmethod',
            unique_together={('lead', 'channel', 'identifier')},
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['lead', '-received_at'], name='core_respon_lead_id_818c93_idx'),
        ),
        migrations.AddIndex(
            model_name='sendqueue',
            index=models.Index(fields=['run_after', 'locked_at'], name='core_sendqu_run_aft_d983ab_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['signal_type', '-detected_at'], name='core_signal_signal__0a89ee_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['source', '-detected_at'], name='core_signal_source_5e3804_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['lead', '-detected_at'], name='core_signal_lead_id_453946_idx'),
        ),
        migrations.AddConstraint(
            model_name='signal',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__gt', '')), fields=('source', 'external_id', 'signal_type'), name='uniq_signal_per_source_item_type'),
        ),
        migrations.AddIndex(
            model_name='outreachlog',
            index=models.Index(fields=['status', 'scheduled_for'], name='core_outrea_status_1607b2_idx'),
        ),
        migrations.AddIndex(
            model_name='outreachlog',
            index=models.Index(fields=['channel', 'sent_at'], name='core_outrea_channel_cdabd5_idx'),
        ),
    ]
